### ISSUE TITLE
[RUN] Resolve apps names

### ISSUE THREAD

**Issue by alex285** [bilelmoussaoui/flatpak-zsh-completion#1]
example app
app name: org.gnome.Builder

Reproduce:
1. type 'flatpak run org.gnome.Bui'
2. press "tab"

Outcome:
org.gnome.Builder_64/stable

Expected (similar to bash implementation)
org.gnome.Builder

**Comment by bilelmoussaoui** [comment]
Should be an easy one to fix!

**Comment by bilelmoussaoui** [comment]
But if you have more than one builder installation with difference architectures? Or different gnome stack versions what should be the output?

**Comment by alex285** [comment]
very good question i dont have an answer, but here is whats happening when we "tab" on ZSH vs BASH completion
flatpak run org.gnome.[tab]

![bashvszsh](https://cloud.githubusercontent.com/assets/11244308/25202878/b87b6b84-255f-11e7-8716-c6272e405a6e.png)

**Comment by alex285** [comment]
i installed
org.gnome.Builder/x86_64/master &
org.gnome.Builder/x86_64/unstable

and Bash again auto-completes `org.gnome.Builder` so you dont now what you are running
so this behavior is `flatpak-bash-completion` bug and not on `flatpak-zsh-completion`

**Comment by bilelmoussaoui** [comment]
We will see what Flatpak guys say about that :)

**Comment by bilelmoussaoui** [comment]
Closing this as zsh > bash regarding completions.
